import { promises as dns } from "node:dns";

/**
 * Real DNS-based email authentication checks for a domain.
 * Uses node:dns to read TXT records — no third-party APIs.
 *
 *  - SPF   : TXT on the domain containing "v=spf1"
 *  - DMARC : TXT on _dmarc.<domain> containing "v=DMARC1"
 *  - DKIM  : TXT on <selector>._domainkey.<domain> containing "v=DKIM1" /
 *            "k=rsa" / "p=". DKIM needs a selector, so we probe the common ones
 *            (Google Workspace uses "google").
 */

const COMMON_DKIM_SELECTORS = [
  "google",
  "default",
  "selector1",
  "selector2",
  "k1",
  "k2",
  "mail",
  "dkim",
  "s1",
  "s2",
];

/** Read TXT records for a name; returns flattened strings or [] if none. */
async function resolveTxt(name) {
  try {
    const records = await dns.resolveTxt(name);
    // Each record is an array of string chunks that must be concatenated.
    return records.map((chunks) => chunks.join(""));
  } catch (err) {
    if (["ENOTFOUND", "ENODATA", "ESERVFAIL"].includes(err.code)) return [];
    throw err;
  }
}

export async function checkSpf(domain) {
  const txts = await resolveTxt(domain);
  const record = txts.find((t) => /v=spf1/i.test(t)) || null;
  return {
    name: "SPF",
    host: domain,
    found: Boolean(record),
    record,
    status: record ? "pass" : "missing",
  };
}

export async function checkDmarc(domain) {
  const host = `_dmarc.${domain}`;
  const txts = await resolveTxt(host);
  const record = txts.find((t) => /v=DMARC1/i.test(t)) || null;

  let status = "missing";
  if (record) {
    // Warn if policy is still p=none (monitoring only).
    status = /p=\s*none/i.test(record) ? "weak" : "pass";
  }
  return { name: "DMARC", host, found: Boolean(record), record, status };
}

export async function checkDkim(domain, selectors = COMMON_DKIM_SELECTORS) {
  for (const selector of selectors) {
    const host = `${selector}._domainkey.${domain}`;
    const txts = await resolveTxt(host);
    const record =
      txts.find((t) => /v=DKIM1|k=rsa|p=/i.test(t)) || null;
    if (record) {
      return {
        name: "DKIM",
        host,
        selector,
        found: true,
        record,
        status: "pass",
      };
    }
  }
  return {
    name: "DKIM",
    host: `<selector>._domainkey.${domain}`,
    selector: null,
    found: false,
    record: null,
    status: "missing",
  };
}

/**
 * Run all three checks and attach recommended records for any that are missing
 * or weak. Recommendations assume Google Workspace (the connect flow is Google).
 */
export async function checkDomainAuth(domain) {
  const [spf, dkim, dmarc] = await Promise.all([
    checkSpf(domain),
    checkDkim(domain),
    checkDmarc(domain),
  ]);

  const recommendations = [];

  if (spf.status !== "pass") {
    recommendations.push({
      type: "SPF",
      host: domain,
      recordType: "TXT",
      value: "v=spf1 include:_spf.google.com ~all",
      why: "Authorizes Google to send mail for your domain. Without it, receivers can't verify your sending source.",
    });
  }

  if (dkim.status !== "pass") {
    recommendations.push({
      type: "DKIM",
      host: "google._domainkey." + domain,
      recordType: "TXT",
      value:
        "(Generate in Google Admin → Apps → Google Workspace → Gmail → Authenticate email, then paste the provided key here.)",
      why: "Cryptographically signs your mail so receivers know it wasn't tampered with. The key is generated by your provider.",
    });
  }

  if (dmarc.status === "missing") {
    recommendations.push({
      type: "DMARC",
      host: "_dmarc." + domain,
      recordType: "TXT",
      value: `v=DMARC1; p=none; rua=mailto:dmarc@${domain}`,
      why: "Tells receivers what to do with mail that fails SPF/DKIM and sends you reports. Start with p=none to monitor.",
    });
  } else if (dmarc.status === "weak") {
    recommendations.push({
      type: "DMARC",
      host: "_dmarc." + domain,
      recordType: "TXT",
      value: `v=DMARC1; p=quarantine; rua=mailto:dmarc@${domain}`,
      why: "You're on p=none (monitor only). Once your mail passes consistently, move to p=quarantine, then p=reject for full protection.",
    });
  }

  const passing = [spf, dkim, dmarc].filter((c) => c.status === "pass").length;

  return {
    domain,
    checks: { spf, dkim, dmarc },
    recommendations,
    summary: {
      passing,
      total: 3,
      allPass: passing === 3,
    },
  };
}
