import LegalLayout, { LegalSection } from "@/components/LegalPageLayout";

export const metadata = {
  title: "Privacy Policy — Trustmailtoday",
  description:
    "How Trustmailtoday collects, uses, and protects your data, including Google account and Gmail access via OAuth.",
};

const CONTACT_EMAIL = "support@trustmailtoday.com";

export default function PrivacyPage() {
  return (
    <LegalLayout title="Privacy Policy" updated="June 14, 2026">
      <p className="text-[15px] leading-relaxed">
        This Privacy Policy explains how Trustmailtoday (&quot;we&quot;,
        &quot;us&quot;, &quot;our&quot;) collects, uses, and protects your
        information when you use our email warmup and deliverability service
        (the &quot;Service&quot;). By using the Service you agree to the
        practices described here.
      </p>

      <LegalSection heading="1. Information we collect">
        <p>We collect only what the Service needs to function:</p>
        <ul className="ml-5 list-disc space-y-1.5">
          <li>
            <strong className="text-white">Account information</strong> — the
            email address of the inbox you connect, used to identify your
            account.
          </li>
          <li>
            <strong className="text-white">Google OAuth tokens</strong> —
            access and refresh tokens issued by Google when you grant
            permission. These let us operate the warmup engine on your behalf.
          </li>
          <li>
            <strong className="text-white">Warmup metadata</strong> — sending
            volume, delivery results, inbox-placement signals, and reputation
            metrics generated by the Service.
          </li>
        </ul>
      </LegalSection>

      <LegalSection heading="2. Google account access and use">
        <p>
          When you connect a Google account, we request the following OAuth
          scopes. We follow the principle of minimal access and request only
          what each feature requires:
        </p>
        <ul className="ml-5 list-disc space-y-1.5">
          <li>
            <code className="text-[#4ADE80]">gmail.send</code> — to send warmup
            emails on your behalf.
          </li>
          <li>
            <code className="text-[#4ADE80]">gmail.modify</code> — to read and
            label warmup messages so we can measure inbox placement (Primary,
            Promotions, or Spam) and reputation.
          </li>
          <li>
            <code className="text-[#4ADE80]">userinfo.email</code> /{" "}
            <code className="text-[#4ADE80]">openid</code> — to identify which
            account you connected.
          </li>
        </ul>
        <p>
          Trustmailtoday&apos;s use and transfer of information received from
          Google APIs adheres to the{" "}
          <a
            href="https://developers.google.com/terms/api-services-user-data-policy"
            target="_blank"
            rel="noopener noreferrer"
            className="text-[#22c55e] underline hover:text-[#4ADE80]"
          >
            Google API Services User Data Policy
          </a>
          , including the Limited Use requirements. We do not use Gmail data for
          advertising, and we do not sell it. We do not allow humans to read
          your email except as required for security, to comply with the law, or
          where you give explicit consent.
        </p>
      </LegalSection>

      <LegalSection heading="3. How we use your information">
        <ul className="ml-5 list-disc space-y-1.5">
          <li>To operate the email warmup engine and adjust sending volume.</li>
          <li>To measure inbox placement and compute your reputation score.</li>
          <li>To provide support and communicate service-related updates.</li>
          <li>To secure the Service and prevent abuse.</li>
        </ul>
      </LegalSection>

      <LegalSection heading="4. Data sharing">
        <p>
          We do not sell your personal data. We share data only with
          infrastructure providers strictly necessary to run the Service (for
          example, hosting and database providers), and only to the extent
          required to deliver the Service to you.
        </p>
      </LegalSection>

      <LegalSection heading="5. Data retention and deletion">
        <p>
          We retain your data only as long as your account is active. You can
          disconnect your inbox at any time from your dashboard, which revokes
          our access and deletes the associated OAuth tokens. To request full
          deletion of your account and associated data, email us at{" "}
          <a
            href={`mailto:${CONTACT_EMAIL}`}
            className="text-[#22c55e] underline hover:text-[#4ADE80]"
          >
            {CONTACT_EMAIL}
          </a>
          . You may also revoke access directly from your{" "}
          <a
            href="https://myaccount.google.com/permissions"
            target="_blank"
            rel="noopener noreferrer"
            className="text-[#22c55e] underline hover:text-[#4ADE80]"
          >
            Google Account permissions
          </a>{" "}
          page.
        </p>
      </LegalSection>

      <LegalSection heading="6. Security">
        <p>
          We use OAuth 2.0 and never see or store your email password. Tokens
          are stored securely and transmitted over encrypted connections. No
          method of transmission or storage is perfectly secure, but we work to
          protect your data using industry-standard safeguards.
        </p>
      </LegalSection>

      <LegalSection heading="7. Your rights">
        <p>
          Depending on your jurisdiction, you may have rights to access,
          correct, export, or delete your personal data. To exercise these
          rights, contact us at{" "}
          <a
            href={`mailto:${CONTACT_EMAIL}`}
            className="text-[#22c55e] underline hover:text-[#4ADE80]"
          >
            {CONTACT_EMAIL}
          </a>
          .
        </p>
      </LegalSection>

      <LegalSection heading="8. Changes to this policy">
        <p>
          We may update this Privacy Policy from time to time. Material changes
          will be reflected by the &quot;Last updated&quot; date above.
        </p>
      </LegalSection>

      <LegalSection heading="9. Contact">
        <p>
          Questions about this policy? Email{" "}
          <a
            href={`mailto:${CONTACT_EMAIL}`}
            className="text-[#22c55e] underline hover:text-[#4ADE80]"
          >
            {CONTACT_EMAIL}
          </a>
          .
        </p>
      </LegalSection>
    </LegalLayout>
  );
}
